---
# tasks file for inventory_config_generator
- name: Generate Inventory playbook configuration
  cisco.catalystcenter.inventory_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    catalystcenter_log_file_path: "{{ inventory_config_generator_catalystcenter_log_file_path }}"
    catalystcenter_log_append: "{{ inventory_config_generator_catalystcenter_log_append }}"
    validate_response_schema: "{{ inventory_config_generator_validate_response_schema }}"
    catalystcenter_api_task_timeout: "{{ inventory_config_generator_catalystcenter_api_task_timeout }}"
    catalystcenter_task_poll_interval: "{{ inventory_config_generator_catalystcenter_task_poll_interval }}"
    state: "{{ inventory_config_generator_state }}"
    config: "{{ inventory_config_generator_config if inventory_config_generator_config is not none else omit }}"
  register: inventory_config_generator_result

- name: Display Inventory generator result
  ansible.builtin.debug:
    var: inventory_config_generator_result
  when: catalystcenter_debug | default(false)
