---
# defaults file for inventory_config_generator
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

inventory_config_generator_catalystcenter_host: null
inventory_config_generator_catalystcenter_port: "443"
inventory_config_generator_catalystcenter_username: "admin"
inventory_config_generator_catalystcenter_password: null
inventory_config_generator_catalystcenter_verify: true
inventory_config_generator_catalystcenter_version: "2.3.7.9"
inventory_config_generator_catalystcenter_debug: false
inventory_config_generator_catalystcenter_log_level: "WARNING"
inventory_config_generator_catalystcenter_log_file_path: "catalystcenter.log"
inventory_config_generator_catalystcenter_log_append: true
inventory_config_generator_catalystcenter_log: false
inventory_config_generator_validate_response_schema: true
inventory_config_generator_catalystcenter_api_task_timeout: 1200
inventory_config_generator_catalystcenter_task_poll_interval: 2
inventory_config_generator_state: "gathered"
inventory_config_generator_config: null
