---
# tasks file for accesspoint
- name: Manage Access Point Configuration
  cisco.catalystcenter.accesspoint_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ accesspoint_state | default('merged') }}"
    config_verify: "{{ accesspoint_config_verify | default(false) }}"
    next_task_after_interval: "{{ accesspoint_next_task_after_interval | default(5) }}"
    config: "{{ accesspoint_config }}"
  register: accesspoint_result

- name: Display Access Point Result
  ansible.builtin.debug:
    var: accesspoint_result
  when: catalystcenter_debug | default(false)
