---
# defaults file for network_profile_switching_config_generator
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

network_profile_switching_config_generator_state: "gathered"
network_profile_switching_config_generator_file_path: null
network_profile_switching_config_generator_file_mode: "overwrite"
network_profile_switching_config_generator_config: null
