---
namespace: cisco
name: catalystcenter
version: 2.7.0
readme: README.md
authors:
  - Rafael Campos <rcampos@cloverhound.com>
  - William Astorga <wastorga@cloverhound.com>
  - Jose Bogarin <jbogarin@cloverhound.com>
  - Bryan Vargas <bvargas@cloverhound.com>
  - Francisco Muñoz <fmunoz@cloverhound.com>
  - Madhan Sankaranarayanan <madsanka@cisco.com>
  - Pawan Singh <pawansi@cisco.com>
  - Rishita Chowdhary (@rishitachowdhary)
  - Muthu Rakesh Babu <mutbabu@cisco.com>
  - Akash Bhaskaran <akabhask@cisco.com>
  - Abinash Mishra <abimishr@cisco.com>
  - Abhishek Maheshwari <abmahesh@cisco.com>
  - Phan Nguyen <phannguy@cisco.com>
  - Rugvedi Kapse <rukapse@cisco.com>
  - Rangaprabhu Deenadayalu <radeenad@cisco.com>
  - Ajith Andrew J <jajandre@cisco.com>
  - Syed Khadeer Ahmed <syedkahm@cisco.com>
description: Ansible Modules, Roles, and Cisco Validated Playbooks (CVP) for Cisco CATALYST Center automation
license_file: "LICENSE"
tags:
  - cisco
  - catalystcenter
  - cloud
  - collection
  - networking
  - sdn
dependencies:
  ansible.utils: ">=2.0.0,<7.0"
repository: https://github.com/cisco-en-programmability/catalystcenter-ansible
documentation: https://cisco-en-programmability.github.io/catalystcenter-ansible/
homepage: https://github.com/cisco-en-programmability/catalystcenter-ansible
issues: https://github.com/cisco-en-programmability/catalystcenter-ansible/issues
build_ignore:
  - .git
  - .gitignore
  - .github
  - .circleci
  - .vscode
  - .pytest_cache

  - .ansible-lint
  - .yamlfmt
  - .yamllint.yml

  - Dockerfile.ansible-test
  - Makefile
  - run_tests.sh

  - Pipfile
  - Pipfile.lock
  - requirements.txt
  - test-requirements.txt

  - "*.tar.gz"

  - cvp/*/tmp/
  - cvp/*/*.log
  - cvp/**/.DS_Store

  - cvp/**/images/**
  - cvp/**/*.png
  - cvp/**/*.jpg
  - cvp/**/*.jpeg
  - cvp/**/*.svg
  - cvp/**/*.pdf
  - cvp/**/*.gif

  - roles/**/images/**
  - roles/**/*.png
  - roles/**/*.jpg
  - roles/**/*.jpeg
  - roles/**/*.svg
  - roles/**/*.pdf
  - roles/**/*.gif

  - "**/__pycache__"
  - "**/*.pyc"
  - "**/*.pyo"

  - "**/.DS_Store"
