---
# tasks file for device_credential_config_generator
- name: Generate Device Credential playbook configuration
  cisco.catalystcenter.device_credential_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    state: "{{ device_credential_config_generator_state }}"
    file_path: "{{ device_credential_config_generator_file_path if device_credential_config_generator_file_path is not none else omit }}"
    file_mode: "{{ device_credential_config_generator_file_mode }}"
    config: "{{ device_credential_config_generator_config if device_credential_config_generator_config is not none else omit }}"
  register: device_credential_config_generator_result

- name: Display Device Credential generator result
  ansible.builtin.debug:
    var: device_credential_config_generator_result
  when: catalystcenter_debug | default(false)
