---
# defaults file for accesspoint
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

accesspoint_state: merged
accesspoint_config_verify: false
accesspoint_next_task_after_interval: 5
accesspoint_config: []
