---
# tasks file for network_profile_wireless
- name: Manage Network Profile Wireless
  cisco.catalystcenter.network_profile_wireless_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ network_profile_wireless_state | default('merged') }}"
    config_verify: "{{ network_profile_wireless_config_verify | default(false) }}"
    config: "{{ network_profile_wireless_config }}"
  register: network_profile_wireless_result

- name: Display Network Profile Wireless Result
  ansible.builtin.debug:
    var: network_profile_wireless_result
  when: catalystcenter_debug | default(false)
