---
# tasks file for sda_host_port_onboarding
- name: Manage SDA Host Port Onboarding
  cisco.catalystcenter.sda_host_port_onboarding_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ sda_host_port_onboarding_state | default('merged') }}"
    config_verify: "{{ sda_host_port_onboarding_config_verify | default(false) }}"
    sda_fabric_port_channel_limit: "{{ sda_host_port_onboarding_sda_fabric_port_channel_limit | default(20) }}"
    config: "{{ sda_host_port_onboarding_config }}"
  register: sda_host_port_onboarding_result

- name: Display SDA Host Port Onboarding Result
  ansible.builtin.debug:
    var: sda_host_port_onboarding_result
  when: catalystcenter_debug | default(false)
