---
# tasks file for lan_automation
- name: Manage LAN Automation
  cisco.catalystcenter.lan_automation_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ lan_automation_state | default('merged') }}"
    config_verify: "{{ lan_automation_config_verify | default(false) }}"
    config: "{{ lan_automation_config }}"
  register: lan_automation_result

- name: Display LAN Automation Result
  ansible.builtin.debug:
    var: lan_automation_result
  when: catalystcenter_debug | default(false)
