---
# defaults file for ise_radius_integration
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

ise_radius_integration_state: merged
ise_radius_integration_config_verify: false
ise_radius_integration_config: []
