---
galaxy_info:
  author: Cisco Systems
  description: Ansible role for managing Catalyst Center Network Profile Switching
  company: Cisco Systems
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Any
      versions:
        - all
  galaxy_tags:
    - cisco
    - catalystcenter
    - networking
    - profile
    - switching

dependencies: []
