---
# tasks file for backup_and_restore_config_generator
- name: Generate Backup And Restore playbook configuration
  cisco.catalystcenter.backup_and_restore_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    state: "{{ backup_and_restore_config_generator_state }}"
    file_path: "{{ backup_and_restore_config_generator_file_path if backup_and_restore_config_generator_file_path is not none else omit }}"
    file_mode: "{{ backup_and_restore_config_generator_file_mode }}"
    config: "{{ backup_and_restore_config_generator_config if backup_and_restore_config_generator_config is not none else omit }}"
  register: backup_and_restore_config_generator_result

- name: Display Backup And Restore generator result
  ansible.builtin.debug:
    var: backup_and_restore_config_generator_result
  when: catalystcenter_debug | default(false)
