---
# defaults file for device_configs_backup
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

device_configs_backup_state: merged
device_configs_backup_config_verify: false
device_configs_backup_config: []
