---
# tasks file for accesspoint_location
- name: Manage Access Point Location
  cisco.catalystcenter.accesspoint_location_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    config_verify: "{{ accesspoint_location_config_verify }}"
    state: "{{ accesspoint_location_state }}"
    config: "{{ accesspoint_location_config }}"
  register: accesspoint_location_result

- name: Display Access Point Location result
  ansible.builtin.debug:
    var: accesspoint_location_result
  when: catalystcenter_debug | default(false)
