---
# defaults file for template
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

template_state: merged
template_config_verify: false
template_config: []
