---
# tasks file for ise_radius_integration
- name: Manage ISE RADIUS Integration
  cisco.catalystcenter.ise_radius_integration_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ ise_radius_integration_state | default('merged') }}"
    config_verify: "{{ ise_radius_integration_config_verify | default(false) }}"
    config: "{{ ise_radius_integration_config }}"
  register: ise_radius_integration_result

- name: Display ISE RADIUS Integration Result
  ansible.builtin.debug:
    var: ise_radius_integration_result
  when: catalystcenter_debug | default(false)
