---
# defaults file for assurance_issue
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

assurance_issue_state: merged
assurance_issue_config_verify: false
assurance_issue_config: []
