---
# tasks file for fabric_devices_info
- name: Manage Fabric Devices Info
  cisco.catalystcenter.fabric_devices_info_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    config_verify: "{{ fabric_devices_info_config_verify }}"
    state: "{{ fabric_devices_info_state }}"
    config: "{{ fabric_devices_info_config }}"
  register: fabric_devices_info_result

- name: Display Fabric Devices Info result
  ansible.builtin.debug:
    var: fabric_devices_info_result
  when: catalystcenter_debug | default(false)
