---
# tasks file for backup_and_restore
- name: Manage Backup And Restore
  cisco.catalystcenter.backup_and_restore_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    config_verify: "{{ backup_and_restore_config_verify }}"
    state: "{{ backup_and_restore_state }}"
    config: "{{ backup_and_restore_config }}"
  register: backup_and_restore_result

- name: Display Backup And Restore result
  ansible.builtin.debug:
    var: backup_and_restore_result
  when: catalystcenter_debug | default(false)
