---
# tasks file for provision_config_generator
- name: Generate Provision playbook configuration
  cisco.catalystcenter.provision_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    state: "{{ provision_config_generator_state }}"
    file_path: "{{ provision_config_generator_file_path if provision_config_generator_file_path is not none else omit }}"
    file_mode: "{{ provision_config_generator_file_mode }}"
    config: "{{ provision_config_generator_config if provision_config_generator_config is not none else omit }}"
  register: provision_config_generator_result

- name: Display Provision generator result
  ansible.builtin.debug:
    var: provision_config_generator_result
  when: catalystcenter_debug | default(false)
