---
# tasks file for reports
- name: Manage Reports
  cisco.catalystcenter.reports_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    config_verify: "{{ reports_config_verify }}"
    state: "{{ reports_state }}"
    config: "{{ reports_config }}"
  register: reports_result

- name: Display Reports result
  ansible.builtin.debug:
    var: reports_result
  when: catalystcenter_debug | default(false)
