---
# defaults file for sda_fabric_sites_zones
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

sda_fabric_sites_zones_state: merged
sda_fabric_sites_zones_config_verify: false
sda_fabric_sites_zones_config: []
