---
# tasks file for network_settings
- name: Manage Network Settings
  cisco.catalystcenter.network_settings_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ network_settings_state | default('merged') }}"
    config_verify: "{{ network_settings_config_verify | default(false) }}"
    config: "{{ network_settings_config }}"
  register: network_settings_result

- name: Display Network Settings Result
  ansible.builtin.debug:
    var: network_settings_result
  when: catalystcenter_debug | default(false)
