---
# defaults file for network_profile_switching
catalystcenter_host: ""
catalystcenter_username: ""
catalystcenter_password: ""
catalystcenter_verify: false
catalystcenter_port: 443
catalystcenter_version: "2.3.7.9"
catalystcenter_debug: false
catalystcenter_log_level: "INFO"
catalystcenter_log: false

network_profile_switching_state: merged
network_profile_switching_config_verify: false
network_profile_switching_config: []
