---
# tasks file for sda_fabric_virtual_networks
- name: Manage SDA Fabric Virtual Networks
  cisco.catalystcenter.sda_fabric_virtual_networks_workflow_manager:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify | default(false) }}"
    catalystcenter_port: "{{ catalystcenter_port | default(443) }}"
    catalystcenter_version: "{{ catalystcenter_version | default('2.3.7.9') }}"
    catalystcenter_debug: "{{ catalystcenter_debug | default(false) }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level | default('INFO') }}"
    catalystcenter_log: "{{ catalystcenter_log | default(false) }}"
    state: "{{ sda_fabric_virtual_networks_state | default('merged') }}"
    config_verify: "{{ sda_fabric_virtual_networks_config_verify | default(false) }}"
    sda_fabric_vlan_limit: "{{ sda_fabric_virtual_networks_sda_fabric_vlan_limit | default(20) }}"
    sda_fabric_gateway_limit: "{{ sda_fabric_virtual_networks_sda_fabric_gateway_limit | default(20) }}"
    config: "{{ sda_fabric_virtual_networks_config }}"
  register: sda_fabric_virtual_networks_result

- name: Display SDA Fabric Virtual Networks Result
  ansible.builtin.debug:
    var: sda_fabric_virtual_networks_result
  when: catalystcenter_debug | default(false)
