---
- name: Generate Application Policy Brownfield Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate all application policy configurations
      cisco.catalystcenter.application_policy_playbook_config_generator:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        catalystcenter_log: true
        catalystcenter_log_level: DEBUG
        state: gathered
        file_path: "tmp/application_policy_generated.yml"
        file_mode: append
        config:
          component_specific_filters:
            components_list: ["queuing_profile"]
            queuing_profile:
              - profile_names_list: ["Enterprise-QoS-Profile", "Enterprise-QoS-Profile"]
            application_policy:
              - policy_names_list: ["wired_traffic_policy", "wireless_traffic_policy"]
