---
- name: Generate YAML Configuration for NFS server details for storing backups
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate YAML Configuration for NFS server details for storing backups
      cisco.catalystcenter.backup_and_restore_playbook_config_generator:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        catalystcenter_log: true
        catalystcenter_log_level: DEBUG
        catalystcenter_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        file_path: "/Users/priyadharshini/Downloads/configuration_details_info"
        file_mode: overwrite
        config:
          component_specific_filters:
            components_list: ["nfs_configuration"]
