---
- name: Generate PnP Brownfield Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate all PnP device configurations
      cisco.catalystcenter.pnp_playbook_config_generator:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        catalystcenter_log: true
        catalystcenter_log_level: DEBUG
        state: gathered
        file_path: "tmp/pnp_device_info.yml"
        file_mode: append
        config:
          component_specific_filters:
            components_list: ["device_info"]
          global_filters:
            device_state: ["Unclaimed"]
