---
# tasks file for rma_config_generator
- name: Generate RMA playbook configuration
  cisco.catalystcenter.rma_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    state: "{{ rma_config_generator_state }}"
    config: "{{ rma_config_generator_config if rma_config_generator_config is not none else omit }}"
  register: rma_config_generator_result

- name: Display RMA generator result
  ansible.builtin.debug:
    var: rma_config_generator_result
  when: catalystcenter_debug | default(false)
