---
# tasks file for pnp_config_generator
- name: Generate PnP playbook configuration
  cisco.catalystcenter.pnp_playbook_config_generator:
    catalystcenter_host: "{{ catalystcenter_host }}"
    catalystcenter_username: "{{ catalystcenter_username }}"
    catalystcenter_password: "{{ catalystcenter_password }}"
    catalystcenter_verify: "{{ catalystcenter_verify }}"
    catalystcenter_port: "{{ catalystcenter_port }}"
    catalystcenter_version: "{{ catalystcenter_version }}"
    catalystcenter_debug: "{{ catalystcenter_debug }}"
    catalystcenter_log_level: "{{ catalystcenter_log_level }}"
    catalystcenter_log: "{{ catalystcenter_log }}"
    state: "{{ pnp_config_generator_state }}"
    file_path: "{{ pnp_config_generator_file_path if pnp_config_generator_file_path is not none else omit }}"
    file_mode: "{{ pnp_config_generator_file_mode }}"
    config: "{{ pnp_config_generator_config if pnp_config_generator_config is not none else omit }}"
  register: pnp_config_generator_result

- name: Display PnP generator result
  ansible.builtin.debug:
    var: pnp_config_generator_result
  when: catalystcenter_debug | default(false)
